# Generated by Django 5.0.6 on 2024-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyshop', '0002_alter_product_image_url_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=1024),
        ),
    ]
